version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules  # Add this line to improve Docker performance with mounted volumes
    ports:
      - 3000:3000
    command: sh -c "npm install && npm run dev"
